// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Services;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Keys", b =>
                {
                    b.Property<string>("KeyPlayer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KeyGame")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("View")
                        .HasColumnType("int");

                    b.HasKey("KeyPlayer");

                    b.HasIndex("KeyPlayer")
                        .IsUnique();

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("WebApplication1.Models.ProcessGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KeyGame")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyPlayer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProcessGame");
                });

            modelBuilder.Entity("WebApplication1.Models.Winners", b =>
                {
                    b.Property<string>("KeyGame")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Winner")
                        .HasColumnType("int");

                    b.HasKey("KeyGame");

                    b.ToTable("Winners");
                });
#pragma warning restore 612, 618
        }
    }
}
